# Generated by Django 6.0.6 on 2026-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
