# Generated by Django 6.0.6 on 2026-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0002_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=100)),
            ],
        ),
    ]
