# Generated by Django 6.0.6 on 2026-07-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0004_student_aadhaar_student_aadhaar_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
