# Generated by Django 6.0.6 on 2026-07-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0005_alter_student_aadhaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
