# Generated by Django 6.0.6 on 2026-07-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0006_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assign_course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhaar_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='character_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='marksheet_10',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='marksheet_12',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='application/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
    ]
