# Generated by Django 6.0.6 on 2026-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0007_student_assign_course_alter_student_aadhaar_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application_status',
            field=models.CharField(default='Not Submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='course_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_verified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
