# Generated by Django 6.0.6 on 2026-07-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0008_student_application_status_student_course_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
