# Generated by Django 6.0.6 on 2026-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0009_remove_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='not assigned', max_length=100),
        ),
    ]
