# Generated by Django 6.0.6 on 2026-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0011_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted')], default='Pending', max_length=20),
        ),
    ]
