# Generated by Django 6.0.6 on 2026-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0012_alter_student_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.TextField(),
        ),
    ]
