# Generated by Django 6.0.6 on 2026-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0013_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='application_status',
            field=models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Not Submitted', max_length=20),
        ),
    ]
